//GET ROOMS
export const GET_ROOMS = "GET_ROOMS";

//GET DETAIL ROOMS
export const GET_DETAILROOMS = "GET_DETAILROOMS";

//GET DETAIL PAYMENT
export const GET_DETAILPAYMENT = "GET_DETAILPAYMENT";

//GET ALL APPROVED
export const GET_ALLAPPROVED = "GET_APPROVED";

//GET ALL APPROVED
export const GET_ALLREPORT = "GET_ALLREPORT";

//GET ALL APPROVED
export const GET_ALLPENDING = "GET_PENDING";
